### ISSUE TITLE
GRASS - poor grassdata performance on NFS

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#356]
Poor grassdata performance on NFS.

See:
- https://trac.osgeo.org/grass/ticket/2185
- http://www.sqlite.org/faq.html#q19

**Comment by landam** [comment]
GRASS allows since r65348 [1]:

1) to configure GRASS data TMPDIR by environmental variable GRASS_TMPDIR_MAPSET
2) force creating vector maps in TMPDIR and move to the current mapset when closing

This allows to overcome poor performance on NFS by pointing TMPDIR to '/mnt/booster', setting GRASS_VECTOR_TEMPORARY to 'move', and GRASS_TMPDIR_MAPSET to '0'.

[1] https://trac.osgeo.org/grass/changeset/65348

**Comment by landam** [comment]
GRASS template updated in 559d3ed
