### ISSUE TITLE
gislab-adduser is failing if non-ascii characters are used in user name

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#404]
Adding user with non-ascii characters in her/his firstname or surname fails (partly), eg.

```
sudo gislab-adduser -g žlutý -l král -m zluty@mail.com zluty 
Successfully added user zluty to LDAP
Successfully set password for user zluty
Error modifying user entry uid=zluty,ou=People,dc=gis,dc=lab in LDAP
```

while

```
sudo gislab-adduser -g zluty -l kral -m zluty@mail.com zluty 
Successfully added user zluty to LDAP
Successfully set password for user zluty
Successfully set encoded password for user uid=zluty,ou=People,dc=gis,dc=lab
[GIS.lab]: Account 'zluty' updated with password 'feigi4za'.
GRANT ROLE
CREATE SCHEMA
GRANT ROLE
[GIS.lab]: Account 'zluty' created with password 'feigi4za'.
```

works.

TODO:
When fixed, please test if non-ascii user name is working in GIS.lab Web

**Comment by mpastor** [comment]
it's because the LDAP 'gecos' attribute has syntax IA5 string, so it does not accept utf-8, but plain ascii. if 'gecos' attribute is missing, the 'cn' attribute is used instead (in GIS.lab these attributes are same). 'cn' attribute support utf-8 encoding. so the simple solution is to remove 3 lines from 'gislab-adduser' admin tool:

```
$ diff -u gislab-adduser.orig gislab-adduser
--- gislab-adduser.orig 2015-05-26 00:38:37.000000000 +0200
+++ gislab-adduser      2015-06-03 00:48:37.464670507 +0200
@@ -89,9 +89,6 @@
 -
 add: mail
 mail: $GISLAB_USER_MAIL
--
-add: gecos
-gecos: $GISLAB_USER_FULL_NAME
 EOL

 if [ -n "$GISLAB_USER_DESC" ]; then
```

MORE ABOUT IT

if you want to use non ascii characters, you should first encode string to the base64 (don't forget to remove '\n' chracter) and add another ':' after the attribute name in ldif file, e.g.:

```
...
cn:: xb5sdXTDvSBrcsOhbA==
...
```

but you can simply use utf-8 string directly (w/o double ':'):

```
...
cn: žlutý král
...
```
be aware then ldap utils return encoded string in base64:

```
# slapcat
...
dn: uid=zluty,ou=People,dc=gis,dc=lab
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
uid: zluty
uidNumber: 3002
gidNumber: 3001
homeDirectory: /mnt/home/zluty
loginShell: /bin/bash
cn:: xb5sdXTDvSBrcsOhbA==
sn:: a3LDoWw=
givenName:: xb5sdXTDvQ== 
mail: zluty@mail.com
...
```

but for example 'getent' is ok:

```
# getent passwd zluty
zluty:x:3002:3001:žlutý král:/mnt/home/zluty:/bin/bash
```

**Comment by imincik** [comment]
@mpastor, do we have some good solution for this problem ?
